DROP USER POKEAPP CASCADE;

CREATE USER pokeapp
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA 10M ON USERS;

GRANT CREATE SESSION TO pokeapp;
GRANT CREATE TABLE TO pokeapp;
GRANT CREATE VIEW TO pokeapp;
GRANT CREATE SEQUENCE TO pokeapp;
